// Generated by LiveScript 1.6.0
"use strict";
window.addEventListener('load', function(){
  var root, formBox, formLogin, formRegister, title, activeForm, a;
  if (root = document.querySelector('#customer_login')) {
    formBox = root.querySelector('div.form-box');
    formLogin = formBox.querySelector('form.login');
    formRegister = formBox.querySelector('form.register');
    title = root.querySelector('h2');
    activeForm = formLogin;
    if (formRegister && formRegister.className.indexOf('hidden') === -1) {
      activeForm = formRegister;
    }
    if (a = activeForm.querySelector('input.first')) {
      a.focus();
      a.select();
    }
    formRegister && function(){
      var form, button, input, time, anim, c;
      form = activeForm === formRegister
        ? [activeForm, formLogin]
        : [activeForm, formRegister];
      button = [form[0].querySelector('button.switch'), form[1].querySelector('button.switch')];
      input = [form[0].querySelector('input.first'), form[1].querySelector('input.first')];
      time = 0.6;
      anim = gsap.timeline({
        paused: true
      });
      anim.add(function(){
        if (anim.reversed()) {
          input[0].focus();
        }
      });
      anim.to(form[0], time / 2, {
        opacity: 0,
        ease: "power3.out"
      });
      anim.set(form[0], {
        display: 'none'
      });
      anim.set(form[1], {
        display: 'block'
      });
      anim.to(form[1], time / 2, {
        opacity: 1,
        ease: "power3.in"
      });
      anim.add(function(){
        if (!anim.reversed()) {
          input[1].focus();
        }
      });
      c = gsap.timeline({
        paused: true
      });
      c.to(title, time / 4, {
        scale: 0.5,
        opacity: 0,
        ease: "back.in"
      });
      c.add(function(){
        if (anim.reversed()) {
          title.innerText = button[1].innerText;
        } else {
          title.innerText = button[0].innerText;
        }
      });
      c.to(title, time / 4, {
        scale: 1,
        opacity: 1,
        clearProps: true,
        ease: "back.out"
      });
      anim.add(c.play(), time / 4);
      button[0].addEventListener('click', function(e){
        e.preventDefault();
        e.stopImmediatePropagation();
        if (!anim.isActive()) {
          anim.play();
        }
      });
      button[1].addEventListener('click', function(e){
        e.preventDefault();
        e.stopImmediatePropagation();
        if (!anim.isActive()) {
          anim.reverse();
        }
      });
    }();
  }
});
