// Generated by LiveScript 1.6.0
"use strict";
window.addEventListener('load', function(){
  var n, o;
  while (n = document.querySelector('#editor')) {
    if (!(n = n.querySelector('.components-panel > div:last-child'))) {
      break;
    }
    o = new MutationObserver(fn$);
    o.observe(n, {
      childList: true
    });
    break;
  }
  function fn$(list, observer){
    observer.disconnect();
    wp.hooks.doAction('carbon-fields.init');
  }
});