// Generated by LiveScript 1.6.0
"use strict";
var slice$ = [].slice, arrayFrom$ = Array.from || function(x){return slice$.call(x);};
(function(){
  /***
  list = [...(document.querySelectorAll 'iframe')]
  for iframe in list when 'src' of iframe.dataset
  	iframe.src = iframe.dataset.src
  /***/
  var a;
  (a = document.querySelector('#search')) && (function(root){
    var list;
    list = arrayFrom$(root.querySelectorAll('.list .product'));
    list.forEach(function(node){
      node.addEventListener('click', async function(e){
        root.classList.add('x');
        node.classList.add('x');
        window.location.assign(node.dataset.href);
      });
    });
  }.call(this, a));
})();