// Generated by LiveScript 1.6.0
"use strict";
var CART, slice$ = [].slice, arrayFrom$ = Array.from || function(x){return slice$.call(x);};
CART = document.querySelector('.sm-blocks.minicart');
CART = CART && (function(root){
  var link, count, smv;
  link = root.querySelector('a');
  count = link.querySelector('.count');
  smv = SM();
  smv.onLoad = function(){
    var a;
    count.firstChild.textContent = a = smv.config.cart.total.count;
    if (a) {
      count.classList.add('v');
    }
  };
  count.addEventListener('click', function(e){
    e.preventDefault();
    e.stopImmediatePropagation();
    console.log('test');
  });
  link.addEventListener('pointerenter', function(){
    link.classList.add('h');
  });
  link.addEventListener('pointerleave', function(){
    link.classList.remove('h');
  });
  return {
    set: function(a){
      count.firstChild.textContent = a;
      count.classList.toggle('v', !!a);
    }
  };
}.call(this, CART));
(function(){
  /***
  list = [...(document.querySelectorAll 'iframe')]
  for iframe in list when 'src' of iframe.dataset
  	iframe.src = iframe.dataset.src
  /***/
  var a;
  (a = document.querySelector('#search')) && (function(root){
    var list;
    list = arrayFrom$(root.querySelectorAll('.list .product'));
    list.forEach(function(node){
      node.addEventListener('click', async function(e){
        root.classList.add('x');
        node.classList.add('x');
        window.location.assign(node.dataset.href);
      });
    });
  }.call(this, a));
})();