// Generated by LiveScript 1.6.0
"use strict";
var slice$ = [].slice, arrayFrom$ = Array.from || function(x){return slice$.call(x);};
window.addEventListener('load', function(){
  (function(){
    var list, i$, len$, iframe;
    list = arrayFrom$(document.querySelectorAll('iframe'));
    for (i$ = 0, len$ = list.length; i$ < len$; ++i$) {
      iframe = list[i$];
      if ('src' in iframe.dataset) {
        iframe.src = iframe.dataset.src;
      }
    }
  })();
  (function(){
    var n, itemSelected, activeDropdown, activeTimer, menuWidth, nodeMap, resizeHandler, deactivateDropdown;
    if (!(n = document.querySelector('#site-navigation ul.menu'))) {
      return;
    }
    itemSelected = false;
    activeDropdown = null;
    activeTimer = null;
    menuWidth = 0;
    nodeMap = {
      menu: n,
      box: arrayFrom$(n.querySelectorAll('li')),
      item: arrayFrom$(n.querySelectorAll('li > a')),
      line: arrayFrom$(n.querySelectorAll('li > hr')),
      dropdown: arrayFrom$(n.querySelectorAll('.dropdown')),
      link: arrayFrom$(n.querySelectorAll('.dropdown > a'))
    };
    resizeHandler = function(){
      var a, i$, ref$, len$, e0, e1, e2, b, c;
      if ((a = nodeMap.menu.clientWidth) === menuWidth) {
        return;
      }
      menuWidth = a;
      for (i$ = 0, len$ = (ref$ = nodeMap.dropdown).length; i$ < len$; ++i$) {
        e0 = ref$[i$];
        e1 = e0.parentNode;
        e2 = e1.parentNode;
        a = e1.getBoundingClientRect();
        b = e2.getBoundingClientRect();
        a = a.left + e0.clientWidth;
        b = b.left + e2.clientWidth;
        if ((c = a - b) > 0) {
          e0.style.left = '-' + c + 'px';
        }
      }
    };
    deactivateDropdown = function(){
      itemSelected = true;
      if (activeTimer) {
        window.clearTimeout(activeTimer);
        activeTimer = 0;
      }
      if (activeDropdown) {
        activeDropdown.timeScale(0.3);
        activeDropdown.reverse();
        activeDropdown = null;
      }
    };
    nodeMap.item.forEach(function(item, index){
      var dropdownTimer, parent, dropdown, svg, submenu, activateDropdown;
      dropdownTimer = 0;
      parent = item.parentNode;
      if (parent.className.indexOf('current-menu') === -1) {
        gsap.set(nodeMap.line[index], {
          visibility: 'visible',
          opacity: 0.4,
          scale: 0
        });
      }
      dropdown = gsap.timeline({
        paused: true
      });
      dropdown.to(nodeMap.line[index], 0.3, {
        scale: 1,
        opacity: 1,
        ease: 'power2.out'
      }, 0);
      if (svg = item.querySelector('svg')) {
        dropdown.to(svg, 0.3, {
          rotate: 90,
          ease: 'power2.out'
        }, 0);
      }
      if (submenu = nodeMap.box[index].querySelector('.dropdown')) {
        gsap.set(submenu, {
          autoAlpha: 0,
          scale: 0.9
        });
        dropdown.to(submenu, 0.3, {
          autoAlpha: 1,
          scale: 1,
          ease: 'power2.inOut'
        }, 0);
      }
      activateDropdown = function(){
        if (activeTimer) {
          window.clearTimeout(activeTimer);
          activeTimer = 0;
        }
        if (activeDropdown && activeDropdown !== dropdown) {
          activeDropdown.reverse();
          activeDropdown = null;
        }
        if (submenu) {
          activeDropdown = dropdown;
        }
        dropdown.play();
      };
      item.addEventListener('pointerenter', function(e){
        e.preventDefault();
        e.stopPropagation();
        if (itemSelected || e.pointerType !== 'mouse') {
          return;
        }
        activateDropdown();
      });
      item.addEventListener('pointerleave', function(e){
        e.preventDefault();
        e.stopPropagation();
        if (itemSelected || e.pointerType !== 'mouse') {
          return;
        }
        if (submenu) {
          if (activeDropdown === dropdown) {
            activeTimer = window.setTimeout(function(){
              activeDropdown.reverse();
              activeDropdown = null;
              activeTimer = 0;
            }, 2000);
          }
        } else {
          dropdown.reverse();
        }
      });
      item.addEventListener('click', function(e){
        e.stopPropagation();
        if (submenu) {
          e.preventDefault();
          if (e.pointerType !== 'mouse') {
            activateDropdown();
          }
        } else {
          deactivateDropdown();
        }
      });
    });
    nodeMap.dropdown.forEach(function(item){
      item.addEventListener('pointerenter', function(e){
        if (activeTimer) {
          window.clearTimeout(activeTimer);
          activeTimer = 0;
        }
      });
      item.addEventListener('pointerleave', function(e){
        if (activeDropdown) {
          activeTimer = window.setTimeout(function(){
            activeDropdown.reverse();
            activeDropdown = null;
            activeTimer = 0;
          }, 2000);
        }
      });
      item.addEventListener('click', function(e){
        e.preventDefault();
        e.stopPropagation();
      });
    });
    nodeMap.link.forEach(function(item){
      var hasNoLink;
      hasNoLink = item.classList.contains('nolink');
      item.addEventListener('click', function(e){
        e.stopPropagation();
        if (hasNoLink) {
          e.preventDefault();
        } else {
          item.classList.add('hovered');
          deactivateDropdown();
        }
      });
    });
    document.addEventListener('click', function(e){
      if (activeDropdown) {
        if (activeTimer) {
          window.clearTimeout(activeTimer);
          activeTimer = 0;
        }
        activeDropdown.reverse();
        activeDropdown = null;
      }
    });
    window.addEventListener('resize', resizeHandler);
    window.dispatchEvent(new Event('resize'));
  })();
  (function(){
    var root, link, svg, cnt, anim;
    root = document.querySelector('.site-cart');
    link = root.querySelector('a');
    svg = link.querySelector('svg');
    cnt = link.querySelector('div > div');
    if (!root.classList.contains('is-current')) {
      anim = gsap.timeline({
        paused: true
      });
      anim.to(cnt, {
        opacity: 0,
        duration: 0.2
      }, 0);
      anim.to(svg, {
        scale: 1.12,
        duration: 0.3,
        ease: 'back'
      }, 0);
      link.addEventListener('click', function(){
        if (anim) {
          anim.play();
        }
        anim = null;
      });
      link.addEventListener('pointerenter', function(){
        if (anim) {
          anim.play();
        }
      });
      link.addEventListener('pointerleave', function(){
        if (anim) {
          anim.reverse();
        }
      });
    }
  })();
  (function(){
    var link;
    if (!(link = document.querySelectorAll('.modern-link'))) {
      return;
    }
    link.forEach(function(node){
      var line, anim;
      if (!(line = node.querySelector('hr'))) {
        return;
      }
      node.classList.remove('noscript');
      if (!node.classList.contains('is-current')) {
        gsap.set(line, {
          opacity: 0,
          scale: 0
        });
        anim = gsap.timeline({
          paused: true
        });
        anim.to(line, {
          opacity: 1,
          scale: 1,
          duration: 0.3,
          ease: "power2.out"
        }, 0);
        node.addEventListener('click', function(){
          if (anim) {
            anim.play();
          }
          anim = null;
        });
        node.addEventListener('pointerenter', function(){
          if (anim) {
            anim.play();
          }
        });
        node.addEventListener('pointerleave', function(){
          if (anim) {
            anim.reverse();
          }
        });
      }
    });
  })();
});